language: R
sudo: false
cache: packages
notifications:
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel
env:
  matrix:
    secure: g5oiBUOSGHGBvUH0igWlBiS02LlkgNxJIAwP7dU/QltduOe2usqOpBIc96Rupe16x8bwhcAICcOvgDGSyQPd+Re96uyB/f15I6qUq8ts6Yq3Y5SqINEbBTdGCWfzYkFGiRDd1nRjvNoXPBkX/rLbHPoJc9B1qRnPIUoOcF4Gjm3LuM0MTEgNJOpju/xUOjM9HDOApv2/B21xOGA4ZGL6W+3pf6wPe2m87npYUV56fxo95oChsdDbj82adWyPSg6dzkia4E/OScaMig4kf/UNSuaiQct3f+ZnMLvU06tllbdonJ1TcrFYGY0aXOfouXHKDnL4oLyEvEHpB/e5PYcrnZHeVUVJydEGYuSZhhty1kdRtew87cNvjB1ZeQcVDAn2ZwLF12HiEHnBh9bJRB9sPoJTo8Fju5jYrpXgbsxujkjMG4urlzDGOk/aa8kEuGy7AhMwldkO9B3dbvjI0yTW1UQscI4NHcEvblIsTfzzd5AuFS1njc6L5x1xYp3+t/7W6EoVrUgADRpwpBDuUzLNewgkbC7jU0y/XIurtQqKj/YJdonoW5pRZY5NsrPb1oGYK9XqjwI1Yl3RJ1ZBEIQduH+k28dFO07r74g6KFe+AUsYMOPhWNtNF+5acGNNYjBhDk5Go3eOLX1PZ0rfgBSRohu8Snh3D8FGiASG+6dUk64=

after_success:
  - Rscript -e 'devtools::install();devtools::test()'